#:schema node_modules/wrangler/config-schema.json
name = "captable-cloud"

main = "./worker.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2025-03-05"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability.logs]
enabled = true

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "bun run build"

[env.staging]
name = "captable-cloud-staging"

[[env.staging.hyperdrive]]
binding = "HYPERDRIVE"
id = "1aece2a80ac74b819949b3632372f5e4"
localConnectionString = "postgresql://postgres:postgres@localhost:5432/captable"
