// Generated by Wrangler by running `wrangler types`
export interface Env {
  NODE_ENV: string;
  DATABASE_URL: string;

  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  BETTER_AUTH_SECRET: string;

  PRIVATE_BUCKET: R2Bucket;
  PUBLIC_BUCKET: R2Bucket;
  HYPERDRIVE: Hyperdrive;
}

declare module "react-router" {
  interface LoaderFunctionArgs {
    context: {
      env: Env;
    };
  }
}
